[package]
name = "llvm-jit"
version = "0.1.0"
authors = ["Flier Lu <flier.lu@gmail.com>"]

[dependencies]
log = "0.3"
error-chain = "0.10"
llvm-sys = "40"

[dev-dependencies]
pretty_env_logger = "0.1"
tempfile = "2"
matches = "0.1"
