[package]
name = "llvm-jit"
version = "0.1.0"
authors = ["Flier Lu <flier.lu@gmail.com>"]

[lib]
doctest = false

[dependencies]
log = "0.3"
error-chain = "0.10"
lazy_static = "0.2"
bitflags = "0.9"
hexplay = "0.1"
libc = "0.2"
llvm-sys = "40"

clippy = {version = "*", optional = true}

[dev-dependencies]
pretty_env_logger = "0.1"
tempfile = "2"
mmap = "0.1"
matches = "0.1"
hamcrest = "*"
crossbeam = "0.3"
