sudo: true
os: linux
dist: trusty

language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  include:
    - os: osx
      osx_image: xcode9.1
      compiler: clang

    - addons:
        apt:
          packages:
            - clang-7
            - g++-5
            - llvm-7-dev
            - libpcap-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-7 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'

env:
  global:
    - RUST_LOG=llvm
    - RUST_BACKTRACE=full
    - LLVM_SYS_70_FFI_WORKAROUND=1

install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      apt-get update && apt-get install llvm-7-dev
      export LLVM_SYS_70_PREFIX=/usr/lib/llvm-7
    else
      brew install llvm libpcap
      export LLVM_SYS_70_PREFIX=`brew --prefix llvm`
    fi
  - export PATH=$LLVM_SYS_70_PREFIX/bin:$PATH
  - llvm-config --version

cache: cargo

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
