sudo: false

language: rust
rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      - clang-7
      - g++-5
      - llvm-7-dev
      - libpcap-dev
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-7
  homebrew:
    packages:
      - llvm
      - libpcap
    update: true

matrix:
  allow_failures:
    - rust: nightly
  include:
    - os: osx
      osx_image: xcode10.1
      compiler: clang
    - os: linux
      dist: trusty

env:
  global:
    - RUST_LOG=llvm
    - RUST_BACKTRACE=full
    - LLVM_SYS_70_FFI_WORKAROUND=1

install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      export LLVM_SYS_70_PREFIX=/usr/lib/llvm-7
    else
      export LLVM_SYS_70_PREFIX=`brew --prefix llvm`
      export PKG_CONFIG_PATH=`brew --prefix libpcap`/lib/pkgconfig
    fi
  - export PATH=$LLVM_SYS_70_PREFIX/bin:$PATH
  - llvm-config --version

cache: cargo

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
