[package]
name = "llvm-wasm"
version = "0.1.0"
authors = ["Flier Lu <flier.lu@gmail.com>"]

[dependencies]
log = "0.4"
failure = "0.1"
parity-wasm = "0.32"

[dev-dependencies]
pretty_env_logger = "0.2"
getopts = "0.2"
